name:        yaml
version:     0.12
synopsis:    Support for parsing and rendering YAML documents.
description: README and API documentation are available at <https://www.stackage.org/package/yaml>
category:    Data
author:      Michael Snoyman <michael@snoyman.com>, Anton Ageev <antage@gmail.com>,Kirill Simonov
maintainer:  Michael Snoyman <michael@snoyman.com>
license:     BSD3
github:      snoyberg/yaml
stability:   stable

extra-source-files:
- test/largest-string.yaml
- test/json.yaml
- test/resources/foo.yaml
- test/resources/bar.yaml
- test/resources/baz.yaml
- test/resources/accent/foo.yaml
- test/resources/loop/foo.yaml
- test/resources/loop/bar.yaml
- test/resources/empty.yaml
- test/resources/empty2.yaml
- README.md
- ChangeLog.md

flags:
  no-exe:
    description: don't install the yaml2json or json2yaml executables
    manual: false
    default: true
  no-examples:
    description: don't build the examples
    manual: false
    default: true

dependencies:
- base >=4.9.1 && <5 # GHC 8.0.2 and later
- bytestring >=0.9.1.4
- transformers >=0.1
- mtl
- conduit >=1.2.8 && <1.4
- resourcet >=0.3 && <1.3
- aeson >=0.11
- containers
- unordered-containers
- vector
- text
- attoparsec >=0.11.3.0
- scientific
- filepath
- directory
- template-haskell
- libyaml >=0.1 && <0.2
when:
  condition: "!impl(ghc >= 8.0)"
  dependencies:
  - fail >= 4.9 && < 4.10
  - semigroups

library:
  other-extensions:
  - LambdaCase
  ghc-options: -Wall
  source-dirs: src

executables:
  json2yaml:
    main: json2yaml.hs
    source-dirs: exe
    dependencies:
    - yaml
    when:
    - condition: flag(no-exe)
      buildable: false
  yaml2json:
    main: yaml2json.hs
    source-dirs: exe
    dependencies:
    - yaml
    when:
    - condition: flag(no-exe)
      buildable: false
  examples:
    main: Main.hs
    source-dirs: examples
    ghc-options: -Wall
    when:
    - condition: flag(no-examples)
      then:
        buildable: false
      else:
        dependencies:
        - raw-strings-qq
        - yaml

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall "-with-rtsopts=-K1K"
    cpp-options: -DTEST
    dependencies:
    - hspec >=1.3
    - HUnit
    - yaml
    - directory
    - mockery
    - base-compat
    - temporary
    - raw-strings-qq
